# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(max_length=120)),
                ('codigo_especialidad', models.CharField(max_length=120)),
                ('dias_incapacidad', models.CharField(max_length=120)),
                ('condicion_usuaria', models.CharField(choices=[(1, 'Embarazo 1er trimestre'), (2, 'Embarazo 2do trimestre'), (3, 'Embarazo 3er trimestre'), (4, 'No embarazada')], default=4, max_length=120)),
                ('conducta', models.CharField(choices=[(1, 'Prescripcion IPS de medicamentos'), (2, 'Ordenacion de procedimientos diagnosticos'), (3, 'Ordenacion de procedimientos terapeuticos'), (4, 'Remision'), (5, 'Interconsulta'), (6, 'Contrereferencia'), (7, 'Orden de hospitalizacion'), (8, 'Control'), (9, 'Ninguna')], default=9, max_length=120)),
                ('causa_extrema', models.CharField(choices=[(1, 'Accidente de IPS trabajo'), (2, 'Accidente de transito'), (3, 'Otro tipo de accidente'), (4, 'Evento catastrofico'), (5, 'Lesion por agresion'), (6, 'Lesion auto inflingida'), (7, 'Maltrato'), (8, 'Enfermedad general'), (9, 'Enfermedad profesional'), (10, 'Otra')], default=10, max_length=120)),
                ('codigo_diagnostico', models.CharField(max_length=120)),
                ('tipo_diagnostico', models.CharField(choices=[('I', 'Impresion diagnostica'), ('N', 'Confirmado nuevo'), ('R', 'Confirmado repetido')], default='I', max_length=1)),
                ('consulta_anual', models.CharField(choices=[('P', 'Primera vez'), ('R', 'Repetida')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('nombres', models.CharField(max_length=120)),
                ('estado_civil', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.CharField(max_length=120)),
                ('sexo', models.CharField(max_length=120)),
                ('ocupacion', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=120)),
                ('aseguradora', models.CharField(max_length=120)),
                ('nombre_acomp', models.CharField(max_length=120)),
                ('tel_acomp', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historia.Paciente'),
        ),
    ]
